//
//  HabitFact.swift
//  finalProject
//
//  Created by Andrew Jenson on 7/15/18.
//  Copyright © 2018 Andrew Jenson. All rights reserved.
//

import Foundation

/*

"Research from Duke University found that more than 40% of the actions people performed each day weren't actual decisions, but habits." - excerpt from "The Power Of Habit" (Prologue)

"Understanding habits is the most important thing I've learned. It's changed everythnig about how I see the world. YOu want to fall asleep fast and wake up feeling good? Pay attention to your nighttime patterns and what you automatically do when you get up. Once you see everything as a bunch of habits, it's like someone gave you a flashlight and a crowbar and you can get to work. There's nothing you can't do if you get the habits right." - excerpt from "The Power Of Habit" (Prologue)

"Habits, scientists say, emerge because the brain is constantly looking for ways to save effort. Left to its own devices, the brain will try to make almost any routine into a habit, because habits allow our minds to ramp down more often. This effort-saving instince is a huge advantage. An efficient brain allows us to stop thinking constantly about basic behaviors, such as walking and choosing what to eat, so we can devote mental energy to inventing spears, irrigation systems, and eventually, airplanes and video games." - excerpt from "The Power Of Habit" (p. 17)

"Within our brains, habits are a three-step process. First there is a cue, a trigger that tells your brain to go into automatic mode and which habit to use. Then there is the routine, which can be physical, mental, or emotional. Finally, there is a reward, which helps your brain figure out if this particular loop is worth remembering for the future. Over time, this loop-cue, routine, reward-becomes more and more automatic. The cue and reward become interwinded until a powerful sense of anticipation and craving emerges. Eventually, a habit is born."  - excerpt from "The Power Of Habit" (p. 19)

"When a habit emerges, the brain stops fully participating in decision making. It stops working so hard, or diverts focus to other task. So unless you deliberately fight a habit-unless you find new routines-the pattern will unfold automatically."

"Habits never really disapper. They're encoded into the structures of our brain, and that's a huge advantage for us, because it would be awful if we had to relearn how to drive after every vacation. The problem is that your brain can't tell the different between bad and good habits, and so if you have a bad one, it's always lurking there, waiting for the right cue and rewards. This explains why it's so hard to create exercise habits or change the way we eat. Once we develop a routine of sitting on the couch, rather than running, or snacking whenever we pass a doughnut shop, those pattens always reamin inside our heads. By the same rule, though, if we learn to create new neurological routines that overpower those behaviors-if we take control of the habit loop-we can force those bad tendencies into the background." - excerpt from "The Power Of Habit" (p.20)

"Studies of people who have successfully started new exercise routines, show they are more likely to stick with a workout plan if they choose a specific cue, such as running as soon as they get home from work, and clear reward, such as a beer or evening of guilt-free television." (p.36)

"Research on dieting says creating new food habits requires a predetermined cue-such as planning menus in advance-and simple rewards for dieters when they stick to their intentions." (p.36)

"New habits are created by putting together a cue, a routine, and a reward, and then cultivating a craving that drives the loop. Take email. When a computer chimes or a smartphone vibrates wiht a new message, the brain starts anticipating the momentary distraction that opening an email provides. On the otherh hand, if someone disables the buzzing-and, thus, removes the cue-people can work for hours without thinking to check their in-boxes." - (p.50)

"Researchers at New Mexico State University studied a group of people who worked out at least three times a week. 92% of people said they habitually exercised because it made them "feel good"-they grew to expect and crave the endorphines and other neurochemicals a workout provided. 67% of people said that working out gave them a sense of "accomplishment"-they had come to crave a regular sense of triumph from tracking their performances, and that self-reward was enough to make the physical activity into a habit. If you want to start exercising each morning, it's essential that you choose a simple cue (like always lacing up your sneakers before breakfast or leaving your workout clothes next to your bed) and a clear reward (such as a midday treat, a sense of accomplishment from working out, or the endorphin rush you get from exercise). Only when your brain starts expecting the reward-will it become automatic to lace up your workout shoes each morning. The cue, in addition to triggering a routine, must also trigger a craving for the reward to come." (p.51)

"Anyone can create habits of his or her own. Want to exercise more? Choose a cue, such as going to the gym as soon as you wake up, and a reward, such as a smoothie, or about the endorphin rush you'll feel. Allow yourself to anticipate the reward. Eventually, that craving will make it easier to push yourself through the gym doors every day." (p.58)

"Of the successful dieters, 78% of them ate breakfast every morning, a meal cued by a time of day. But most of the successful dieters also envisioned a specific reward for sticking with their diet-a bikini they wanted to wear or the sense of pride they felt when they stepped on the scale each day-something they chose carefully and really wanted. They focused on the craving for that reward when temptations arose, cultivated the craving into a mild obsession. And their craving for that reward, researchers found, crowded out the temptation to drop the diet. The craving drove the habit loop." (p.59)

 For you to create a new habit, you need to have a strong belief that you can do it. In her book Mindset: The New Psychology of Success, Stanford Professor Dr. Carol Dweck states that having a growth, or a “I can do it”, mindset is key to outperforming those with a fixed mindset. If you believe that you can’t do something, then you won’t do it. However, if you believe that you can achieve something, you’ll at least attempt to do it. (p.???)

"Researchers figured out that belief made the difference between ___?????????!!!!. Once people learned how to believe in something, that skill started spilling over to other parts of their lives, until they started believing they could change. Belief was the ingredient that made a reworked habit loop into a permanent behavior. You don't have to believe in God, but you do need to capacity to believe that things will get better." (p.85)

"Studies found that when people habitually exercising, even as infrequently as once a week, they start changing other, unrelated patterns in their lives, often unknowingly. Typically, people who exercise start eating better and becoming more productive at work. They smoke less and show more patience with colleagues and family. They use their credit cards less frequently and say they feel less stressed. It's not completely clear why. But for many people, exercise is a keystone habit that triggers widespread change. There's something about it that makes other good habits easier." (p.108)

"Studies have documented that families who habitually eat dinner together seem to raise children with better homework skills, higher grades, greater emotional control, and more confidence. Somehow this inital shift start chain reactions that help other good habits take hold." (p.109)


"Making your bed every morning is correlated with better productivity, a great sense of well-being and stronger skills at sticking with a budget. Somehow this inital shift start chain reactions that help other good habits take hold." (p.109)

"When Michael Phelps was younger, each night before falling asleep and each orning after waking up, Phelps would imagine himeself jumping off the blocks and, in slow motion, swimming flawlessly. He would lie in bed with his eyes shut and watch the entire competition, the smallest details, again and again, until he knew each second by heart. During practice, he got faster and faster." (p.111)

"Small wins are part of how keystone habits create widespread changes. A huge body of research has shown that small wins have enormous power, an influence disproportionate to the accomplishments of the victories themselves. Small wins are a steady application of a small advantage. Once a small win has been accomplished, forces are set in motion that favor another small win. Small wins fuel transformative changes by leveraging tiny advantages into small patterns that convince people that bigger achievements are within reach." (p.112)

"The National Institutes of Healthy published a study where they asked obese people to concentrate on writing down everything they ate at least one day a week.  It was hard at first. Slowly, however, people started recording their meals once a week-and sometimes, more often. Eventually it became a habit. Six months into the study, people who kept daily food records had lost twice as much weight as everyone else." (p.121)

"Dozens of studies show that willpower is the single most important keystone habit for individual success. In a 2005 study, for instance, the University of Pennsylvania analyzed 164 eighth-grade students, measuring their IQs and other factors, including how much willpower the students demonstrated, as measured by tests of their self-discipline. Students who exerted high levels of willpower were more likely to earn higher grades in their classes and gain admission into more selective schoools. They had fewer absences and spent less time watching television and more hours on homework. Highly self-disciplined adolescents outperformed their more impulsive peeers on every academic-performance variable. Self-discipline predicted academic performance more robustly than did IQ. Self-discipline also predicted which students would improve their grades over the course of the school year, whereas IQ did not. Self-discipline has a bigger effect on academic performance than does intellectual talent. And the best way to strengthen willpower and give students a leg up, studies indicate, is to make it into a habit so that willpower occurs without them having to think about it." (p.131)

*/
struct HabitFact {

    static let am0 = CounterAdvice(quote: "Research from Duke University found that more than 40% of the actions people performed each day weren't actual decisions, but habits.", source: "The Power of Habit by Charles Duhigg")

    static let pm0 = CounterAdvice(quote: "Habits, scientists say, emerge because the brain is constantly looking for ways to save effort. Left to its own devices, the brain will try to make almost any routine into a habit, because habits allow our minds to ramp down more often. This effort-saving instince is a huge advantage. An efficient brain allows us to stop thinking constantly about basic behaviors, such as walking and choosing what to eat.", source: "The Power of Habit by Charles Duhigg")

    static let pm1 = CounterAdvice(quote: "Within our brains, habits are a three-step process. First there is a cue, a trigger that tells your brain to go into automatic mode and which habit to use. Then there is the routine, which can be physical, mental, or emotional. Finally, there is a reward, which helps your brain figure out if this particular loop is worth remembering for the future. Over time, this loop-cue, routine, reward-becomes more and more automatic. Eventually, a habit is born.", source: "The Power of Habit by Charles Duhigg")


    static let am1 = CounterAdvice(quote: "\"You don’t have to change dozens of habits to get to your goals.  You only have to change a few keystone habits that will have a ripple effect on your outcomes. A huge body of research has shown that small wins have enormous power, an influence disproportionate to the accomplishments of the victories themselves. Once a small win has been accomplished, forces are set in motion that favor another small win. Small wins fuel transformative changes by leveraging tiny advantages into small patterns that convince people that bigger achievements are within reach.\"", source: "The Power of Habit by Charles Duhigg")

    static let am2 = CounterAdvice(quote: "When a habit emerges, the brain stops fully participating in decision making. It stops working so hard, or diverts focus to other task. So unless you deliberately fight a habit-unless you find new routines-the pattern will unfold automatically.", source: "The Power of Habit by Charles Duhigg")

    static let pm2 = CounterAdvice(quote: "Habits never really disapper. They're encoded into the structures of our brain, and that's a huge advantage for us, because it would be awful if we had to relearn how to drive after every vacation. The problem is that your brain can't tell the different between bad and good habits, and so if you have a bad one, it's always lurking there, waiting for the right cue and rewards. This explains why it's so hard to create exercise habits or change the way we eat. Once we develop a routine of sitting on the couch, rather than running, or snacking whenever we pass a doughnut shop, those pattens always reamin inside our heads. By the same rule, though, if we learn to create new neurological routines that overpower those behaviors-if we take control of the habit loop-we can force those bad tendencies into the background.", source: "The Power of Habit by Charles Duhigg")

    static let am3 = CounterAdvice(quote: "Studies of people who have successfully started new exercise routines, show they are more likely to stick with a workout plan if they choose a specific cue, such as running as soon as they get home from work, and clear reward, such as a beer or evening of guilt-free television.", source: "The Power of Habit by Charles Duhigg")

    static let pm3 = CounterAdvice(quote: "Research on dieting says creating new food habits requires a predetermined cue-such as planning menus in advance-and simple rewards for dieters when they stick to their intentions.", source: "The Power of Habit by Charles Duhigg")

    static let am4 = CounterAdvice(quote: "Researchers at New Mexico State University studied a group of people who worked out at least three times a week. 92% of people said they habitually exercised because it made them \"feel good\"-they grew to expect and crave the endorphines and other neurochemicals a workout provided. 67% of people said that working out gave them a sense of \"accomplishment\"-they had come to crave a regular sense of triumph from tracking their performances, and that self-reward was enough to make the physical activity into a habit. If you want to start exercising each morning, it's essential that you choose a simple cue (like always lacing up your sneakers before breakfast or leaving your workout clothes next to your bed) and a clear reward (such as a midday treat, a sense of accomplishment from working out, or the endorphin rush you get from exercise). Only when your brain starts expecting the reward-will it become automatic to lace up your workout shoes each morning. The cue, in addition to triggering a routine, must also trigger a craving for the reward to come.", source: "The Power of Habit by Charles Duhigg")

    static let pm4 = CounterAdvice(quote: "Anyone can create habits of his or her own. Want to exercise more? Choose a cue, such as going to the gym as soon as you wake up, and a reward, such as a smoothie, or about the endorphin rush you'll feel. Allow yourself to anticipate the reward. Eventually, that craving will make it easier to push yourself through the gym doors every day.", source: "The Power of Habit by Charles Duhigg")

    static let am5 = CounterAdvice(quote: "New habits are created by putting together a cue, a routine, and a reward, and then cultivating a craving that drives the loop. Take email. When a computer chimes or a smartphone vibrates wiht a new message, the brain starts anticipating the momentary distraction that opening an email provides. On the otherh hand, if someone disables the buzzing-and, thus, removes the cue-people can work for hours without thinking to check their in-boxes.", source: "The Power of Habit by Charles Duhigg")

    static let pm5 = CounterAdvice(quote: "Of the successful dieters, 78% of them ate breakfast every morning, a meal cued by a time of day. But most of the successful dieters also envisioned a specific reward for sticking with their diet-a bikini they wanted to wear or the sense of pride they felt when they stepped on the scale each day-something they chose carefully and really wanted. They focused on the craving for that reward when temptations arose, cultivated the craving into a mild obsession. And their craving for that reward, researchers found, crowded out the temptation to drop the diet. The craving drove the habit loop.", source: "The Power of Habit by Charles Duhigg")

    static let am6 = CounterAdvice(quote: "For you to create a new habit, you need to have a strong belief that you can do it. In her book Mindset: The New Psychology of Success, Stanford Professor Dr. Carol Dweck states that having a growth, or a \"I can do it\", mindset is key to outperforming those with a fixed mindset. If you believe that you can’t do something, then you won’t do it. However, if you believe that you can achieve something, you’ll at least attempt to do it.", source: "The Power of Habit by Charles Duhigg")

    static let pm6 = CounterAdvice(quote: "Studies found that when people habitually exercising, even as infrequently as once a week, they start changing other, unrelated patterns in their lives, often unknowingly. Typically, people who exercise start eating better and becoming more productive at work. They smoke less and show more patience with colleagues and family. They use their credit cards less frequently and say they feel less stressed. It's not completely clear why. But for many people, exercise is a keystone habit that triggers widespread change. There's something about it that makes other good habits easier.", source: "The Power of Habit by Charles Duhigg")
}
